services:
  app_be:
    build:

      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    environment:
      OPENSSL_CONF: /etc/ssl/
    networks:
      - ipbi_network
    volumes:
      - ./backend/public:./public
  app_fe: 
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:4000
    networks:
      - ipbi_network
  db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ipbi_pgdata:/var/lib/postgresql/data
    networks:
      - ipbi_network

volumes:
  ipbi_pgdata:

networks:
  ipbi_network:
    driver: bridge